---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-boostrap-admin-credentials
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: idp
  namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: local-keycloak
