---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: base-app
    app.kubernetes.io/part-of: my-app
    app.kubernetes.io/name: my-app
  name: my-app-oauth-secrets
  namespace: my-app
type: Opaque
data:
  cookie-secret: "WFhYWFhYWFhYWFhYWFhYWA=="
  client-secret: "YmVNMWV3dk9FVEJ6dk1TVUVSMExURHptYlBqUEVNenEK"
  client-id: "b2F1dGgtcHJveHktdGVzdAo="
  oidc-provider-ca.pem: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJyVENDQVZTZ0F3SUJBZ0lRRW1sckxscFFIQ1ZHd2R2cUVyZ3BkekFLQmdncWhrak9QUVFEQWpBa01TSXcKSUFZRFZRUURFeGxyWlhsamJHOWhheTR4TWpjdU1DNHdMakV1Ym1sd0xtbHZNQjRYRFRJMU1EVXhPVEUxTURZMQpNRm9YRFRJMU1EZ3hOekUxTURZMU1Gb3dKREVpTUNBR0ExVUVBeE1aYTJWNVkyeHZZV3N1TVRJM0xqQXVNQzR4CkxtNXBjQzVwYnpCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkQ3eGpuWTVaVzJjcGF1TWt0SnMKL21QaWFoeVIycjdEbUNoa2RXaDNzV1A0RWExY0pDVTJrZE1MZFkzT0ptNlUrWnVCczAzNUpDUmdrdnBHWCtBUwpPa1NqYURCbU1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUldMb3FyQlcwaE1pSHpBVlZ0S1VYUGFTWlVtakFrQmdOVkhSRUVIVEFiZ2hsclpYbGpiRzloYXk0eE1qY3UKTUM0d0xqRXVibWx3TG1sdk1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lHRFI1UW1hQTFsblduRXV5NStjNC9ISApJS2hhVWRKblFOeTl2SW11bFdodkFpQTRlUXp6dVNQTW4vTzFtUjlMRk5Ca0sxZzErTGJ0clhKK05jME80YWc5CmJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
