// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID          uuid.UUID
	Name        string
	EmailDomain pgtype.Text
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedBy   string
	UpdatedBy   string
}

type TenantUser struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	IsActive          bool
	ExternalID        string
	Email             string
	PreferredUsername pgtype.Text
	Locale            string
	AppTheme          string
	HourlyRate        float32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatedBy         string
	UpdatedBy         string
}
