// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenant.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, email_domain, is_active, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email_domain, is_active, created_at, updated_at, created_by, updated_by
`

type CreateTenantParams struct {
	Name        string
	EmailDomain pgtype.Text
	IsActive    bool
	CreatedBy   string
	UpdatedBy   string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.EmailDomain,
		arg.IsActive,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, email_domain, is_active, created_at, updated_at, created_by, updated_by
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, email_domain, is_active, created_at, updated_at, created_by, updated_by
FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailDomain,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    name = COALESCE($2, name),
    email_domain = COALESCE($3, email_domain),
    is_active = COALESCE($4, is_active),
    updated_at = now(),
    updated_by = $5
WHERE id = $1
RETURNING id, name, email_domain, is_active, created_at, updated_at, created_by, updated_by
`

type UpdateTenantParams struct {
	ID          uuid.UUID
	Name        string
	EmailDomain pgtype.Text
	IsActive    bool
	UpdatedBy   string
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.EmailDomain,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailDomain,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
