// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenant_user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantUser = `-- name: CreateTenantUser :one
INSERT INTO tenant_user (
    tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, COALESCE($6, 'hr'), COALESCE($7, 'dark'), $8, $9, $10
)
RETURNING id, tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_at, updated_at, created_by, updated_by
`

type CreateTenantUserParams struct {
	TenantID          uuid.UUID
	IsActive          bool
	ExternalID        string
	Email             string
	PreferredUsername pgtype.Text
	Column6           interface{}
	Column7           interface{}
	HourlyRate        float32
	CreatedBy         string
	UpdatedBy         string
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, createTenantUser,
		arg.TenantID,
		arg.IsActive,
		arg.ExternalID,
		arg.Email,
		arg.PreferredUsername,
		arg.Column6,
		arg.Column7,
		arg.HourlyRate,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IsActive,
		&i.ExternalID,
		&i.Email,
		&i.PreferredUsername,
		&i.Locale,
		&i.AppTheme,
		&i.HourlyRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTenantUserByID = `-- name: GetTenantUserByID :one
SELECT id, tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_at, updated_at, created_by, updated_by
FROM tenant_user
WHERE id = $1
`

func (q *Queries) GetTenantUserByID(ctx context.Context, id uuid.UUID) (TenantUser, error) {
	row := q.db.QueryRow(ctx, getTenantUserByID, id)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IsActive,
		&i.ExternalID,
		&i.Email,
		&i.PreferredUsername,
		&i.Locale,
		&i.AppTheme,
		&i.HourlyRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const setTenantUserActiveStatus = `-- name: SetTenantUserActiveStatus :one
UPDATE tenant_user
SET is_active = $2,
    updated_at = now(),
    updated_by = $3
WHERE id = $1
RETURNING id, tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_at, updated_at, created_by, updated_by
`

type SetTenantUserActiveStatusParams struct {
	ID        uuid.UUID
	IsActive  bool
	UpdatedBy string
}

func (q *Queries) SetTenantUserActiveStatus(ctx context.Context, arg SetTenantUserActiveStatusParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, setTenantUserActiveStatus, arg.ID, arg.IsActive, arg.UpdatedBy)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IsActive,
		&i.ExternalID,
		&i.Email,
		&i.PreferredUsername,
		&i.Locale,
		&i.AppTheme,
		&i.HourlyRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateTenantUserHourlyRate = `-- name: UpdateTenantUserHourlyRate :one
UPDATE tenant_user
SET
    hourly_rate = $2,
    updated_at = now(),
    updated_by = $3
WHERE id = $1
RETURNING id, tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_at, updated_at, created_by, updated_by
`

type UpdateTenantUserHourlyRateParams struct {
	ID         uuid.UUID
	HourlyRate float32
	UpdatedBy  string
}

func (q *Queries) UpdateTenantUserHourlyRate(ctx context.Context, arg UpdateTenantUserHourlyRateParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, updateTenantUserHourlyRate, arg.ID, arg.HourlyRate, arg.UpdatedBy)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IsActive,
		&i.ExternalID,
		&i.Email,
		&i.PreferredUsername,
		&i.Locale,
		&i.AppTheme,
		&i.HourlyRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateTenantUserProfile = `-- name: UpdateTenantUserProfile :one
UPDATE tenant_user
SET
    locale = COALESCE($2, locale),
    app_theme = COALESCE($3, app_theme),
    updated_at = now(),
    updated_by = $4
WHERE id = $1
RETURNING id, tenant_id, is_active, external_id, email, preferred_username, locale, app_theme, hourly_rate, created_at, updated_at, created_by, updated_by
`

type UpdateTenantUserProfileParams struct {
	ID        uuid.UUID
	Locale    string
	AppTheme  string
	UpdatedBy string
}

func (q *Queries) UpdateTenantUserProfile(ctx context.Context, arg UpdateTenantUserProfileParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, updateTenantUserProfile,
		arg.ID,
		arg.Locale,
		arg.AppTheme,
		arg.UpdatedBy,
	)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IsActive,
		&i.ExternalID,
		&i.Email,
		&i.PreferredUsername,
		&i.Locale,
		&i.AppTheme,
		&i.HourlyRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
