apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/keycloak-operator/
  - ../../base/cloudnative-pg/
  - ../../base/ingress-nginx/
  - ../../base/cert-manager/
  - ./cluster-issuer.yaml
